export const Caloriesdata=[
    {
      "Food and Serving": "",
      "Calories": "",
      "Calories�from Fat": "",
      "Total Fat": "(g)",
      "Total Fat__1": "(%DV)",
      "Sodium": "(g)",
      "Sodium__1": "(%DV)",
      "Potassium": "(g)",
      "Potassium__1": "(%DV)",
      "Total Carbo-hydrate": "(g)",
      "Total Carbo-hydrate__1": "(%DV)",
      "Dietary Fiber": "(g)",
      "Dietary Fiber__1": "(%DV)",
      "Sugars": "(g)",
      "Protein": "(g)",
      "Vitamin A": "(%DV)",
      "Vitamin C": "(%DV)",
      "Calcium": "(%DV)",
      "��Iron��": "(%DV)",
      "Saturated Fat": "(%DV)",
      "Saturated Fat__1": "(mg)�",
      "Chole-sterol": "(%DV)",
      "Chole-sterol__1": "(mg)�",
      "Food Type": ""
    },
    {
      "Food and Serving": "Asparagus, 5 spears (93 g/3.3 oz)",
      "Calories": 20,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 230,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 4,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 2,
      "Protein": 2,
      "Vitamin A": 10,
      "Vitamin C": 15,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Bell Pepper, 1 medium (148 g/5.3 oz)",
      "Calories": 25,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 40,
      "Sodium__1": 2,
      "Potassium": 220,
      "Potassium__1": 6,
      "Total Carbo-hydrate": 6,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 4,
      "Protein": 1,
      "Vitamin A": 4,
      "Vitamin C": 190,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Broccoli, 1 medium stalk (148 g/5.3 oz)",
      "Calories": 45,
      "Calories�from Fat": 0,
      "Total Fat": 0.5,
      "Total Fat__1": 1,
      "Sodium": 80,
      "Sodium__1": 3,
      "Potassium": 460,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 8,
      "Total Carbo-hydrate__1": 3,
      "Dietary Fiber": 3,
      "Dietary Fiber__1": 12,
      "Sugars": 2,
      "Protein": 4,
      "Vitamin A": 6,
      "Vitamin C": 220,
      "Calcium": 6,
      "��Iron��": 6,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Carrot, 1 carrot, 7\" long,�1 1/4\" diameter (78 g/2.8 oz)",
      "Calories": 30,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 60,
      "Sodium__1": 3,
      "Potassium": 250,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 7,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 5,
      "Protein": 1,
      "Vitamin A": 110,
      "Vitamin C": 10,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Cauliflower, 1/6 medium head (99 g/3.5 oz)",
      "Calories": 25,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 30,
      "Sodium__1": 1,
      "Potassium": 270,
      "Potassium__1": 8,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 2,
      "Protein": 2,
      "Vitamin A": 0,
      "Vitamin C": 100,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Celery, 2 medium stalks (110 g/3.9 oz)",
      "Calories": 15,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 115,
      "Sodium__1": 5,
      "Potassium": 260,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 4,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 2,
      "Protein": 0,
      "Vitamin A": 10,
      "Vitamin C": 15,
      "Calcium": 4,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Cucumber, 1/3 medium (99 g/3.5 oz)",
      "Calories": 10,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 140,
      "Potassium__1": 4,
      "Total Carbo-hydrate": 2,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 1,
      "Protein": 1,
      "Vitamin A": 4,
      "Vitamin C": 10,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Green (Snap) Beans, 3/4 cup cut (83 g/3.0 oz)",
      "Calories": 20,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 200,
      "Potassium__1": 6,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 3,
      "Dietary Fiber__1": 12,
      "Sugars": 2,
      "Protein": 1,
      "Vitamin A": 4,
      "Vitamin C": 10,
      "Calcium": 4,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Green�Cabbage, 1/12 medium head (84 g/3.0 oz)",
      "Calories": 25,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 20,
      "Sodium__1": 1,
      "Potassium": 190,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 3,
      "Protein": 1,
      "Vitamin A": 0,
      "Vitamin C": 70,
      "Calcium": 4,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Green Onion, 1/4 cup chopped (25 g/0.9 oz)",
      "Calories": 10,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 10,
      "Sodium__1": 0,
      "Potassium": 70,
      "Potassium__1": 2,
      "Total Carbo-hydrate": 2,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 1,
      "Protein": 0,
      "Vitamin A": 2,
      "Vitamin C": 8,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Iceberg Lettuce, 1/6 medium head (89 g/3.2 oz)",
      "Calories": 10,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 10,
      "Sodium__1": 0,
      "Potassium": 125,
      "Potassium__1": 4,
      "Total Carbo-hydrate": 2,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 2,
      "Protein": 1,
      "Vitamin A": 6,
      "Vitamin C": 6,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Leaf Lettuce, 1 1/2 cups shredded (85 g/3.0 oz)",
      "Calories": 15,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 35,
      "Sodium__1": 1,
      "Potassium": 170,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 2,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 1,
      "Protein": 1,
      "Vitamin A": 130,
      "Vitamin C": 6,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Mushrooms, 5 medium (84 g/3.0 oz)",
      "Calories": 20,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 15,
      "Sodium__1": 0,
      "Potassium": 300,
      "Potassium__1": 9,
      "Total Carbo-hydrate": 3,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 0,
      "Protein": 3,
      "Vitamin A": 0,
      "Vitamin C": 2,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Onion, 1 medium (148 g/5.3 oz)",
      "Calories": 45,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 5,
      "Sodium__1": 0,
      "Potassium": 190,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 11,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 3,
      "Dietary Fiber__1": 12,
      "Sugars": 9,
      "Protein": 1,
      "Vitamin A": 0,
      "Vitamin C": 20,
      "Calcium": 4,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Potato, 1 medium (148 g/5.3 oz)",
      "Calories": 110,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 620,
      "Potassium__1": 18,
      "Total Carbo-hydrate": 26,
      "Total Carbo-hydrate__1": 9,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 1,
      "Protein": 3,
      "Vitamin A": 0,
      "Vitamin C": 45,
      "Calcium": 2,
      "��Iron��": 6,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Radishes, 7 radishes (85 g/3.0 oz)",
      "Calories": 10,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 55,
      "Sodium__1": 2,
      "Potassium": 190,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 3,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 2,
      "Protein": 0,
      "Vitamin A": 0,
      "Vitamin C": 30,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Summer�Squash, 1/2 medium (98 g/3.5 oz)",
      "Calories": 20,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 260,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 4,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 2,
      "Protein": 1,
      "Vitamin A": 6,
      "Vitamin C": 30,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Sweet Corn, kernels from 1�medium ear (90 g/3.2 oz)",
      "Calories": 90,
      "Calories�from Fat": 20,
      "Total Fat": 2.5,
      "Total Fat__1": 4,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 250,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 18,
      "Total Carbo-hydrate__1": 6,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 5,
      "Protein": 4,
      "Vitamin A": 2,
      "Vitamin C": 10,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Sweet Potato, 1 medium, 5\" long,�2\" diameter (130 g/4.6 oz)",
      "Calories": 100,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 70,
      "Sodium__1": 3,
      "Potassium": 440,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 23,
      "Total Carbo-hydrate__1": 8,
      "Dietary Fiber": 4,
      "Dietary Fiber__1": 16,
      "Sugars": 7,
      "Protein": 2,
      "Vitamin A": 120,
      "Vitamin C": 30,
      "Calcium": 4,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Tomato, 1 medium (148 g/5.3 oz)",
      "Calories": 25,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 20,
      "Sodium__1": 1,
      "Potassium": 340,
      "Potassium__1": 10,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 3,
      "Protein": 1,
      "Vitamin A": 20,
      "Vitamin C": 40,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Vegetables, Serving Size (gram weight/�ounce weight)"
    },
    {
      "Food and Serving": "Apple, 1 large (242 g/8 oz)",
      "Calories": 130,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 260,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 34,
      "Total Carbo-hydrate__1": 11,
      "Dietary Fiber": 5,
      "Dietary Fiber__1": 20,
      "Sugars": 25,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 8,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Avocado, California,1/5 medium (30 g/1.1 oz)",
      "Calories": 50,
      "Calories�from Fat": 35,
      "Total Fat": 4.5,
      "Total Fat__1": 7,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 140,
      "Potassium__1": 4,
      "Total Carbo-hydrate": 3,
      "Total Carbo-hydrate__1": 1,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 0,
      "Protein": 1,
      "Vitamin A": 0,
      "Vitamin C": 4,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Banana, 1 medium (126 g/4.5 oz)",
      "Calories": 110,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 450,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 30,
      "Total Carbo-hydrate__1": 10,
      "Dietary Fiber": 3,
      "Dietary Fiber__1": 12,
      "Sugars": 19,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 15,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Cantaloupe, 1/4 medium (134 g/4.8 oz)",
      "Calories": 50,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 20,
      "Sodium__1": 1,
      "Potassium": 240,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 12,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 11,
      "Protein": 1,
      "Vitamin A": 120,
      "Vitamin C": 80,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Grapefruit, 1/2 medium, (154 g/5.5 oz)",
      "Calories": 60,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 160,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 15,
      "Total Carbo-hydrate__1": 5,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 11,
      "Protein": 1,
      "Vitamin A": 35,
      "Vitamin C": 100,
      "Calcium": 4,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Grapes, 3/4 cup (126 g/4.5 oz)",
      "Calories": 90,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 15,
      "Sodium__1": 1,
      "Potassium": 240,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 23,
      "Total Carbo-hydrate__1": 8,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 20,
      "Protein": 0,
      "Vitamin A": 0,
      "Vitamin C": 2,
      "Calcium": 2,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Honeydew�Melon 1/10 medium�melon  (134 g/4.8 oz)",
      "Calories": 50,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 30,
      "Sodium__1": 1,
      "Potassium": 210,
      "Potassium__1": 6,
      "Total Carbo-hydrate": 12,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 11,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 45,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Kiwifruit, 2 medium (148 g/5.3 oz)",
      "Calories": 90,
      "Calories�from Fat": 10,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 450,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 20,
      "Total Carbo-hydrate__1": 7,
      "Dietary Fiber": 4,
      "Dietary Fiber__1": 16,
      "Sugars": 13,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 240,
      "Calcium": 4,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Lemon, 1 medium (58 g/2.1 oz)",
      "Calories": 15,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 75,
      "Potassium__1": 2,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 2,
      "Protein": 0,
      "Vitamin A": 0,
      "Vitamin C": 40,
      "Calcium": 2,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Lime, 1 medium (67 g/2.4 oz)",
      "Calories": 20,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 75,
      "Potassium__1": 2,
      "Total Carbo-hydrate": 7,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 0,
      "Protein": 0,
      "Vitamin A": 0,
      "Vitamin C": 35,
      "Calcium": 0,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Nectarine, 1 medium (140 g/5.0 oz)",
      "Calories": 60,
      "Calories�from Fat": 5,
      "Total Fat": 0.5,
      "Total Fat__1": 1,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 250,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 15,
      "Total Carbo-hydrate__1": 5,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 11,
      "Protein": 1,
      "Vitamin A": 8,
      "Vitamin C": 15,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Orange, 1 medium (154 g/5.5 oz)",
      "Calories": 80,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 250,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 19,
      "Total Carbo-hydrate__1": 6,
      "Dietary Fiber": 3,
      "Dietary Fiber__1": 12,
      "Sugars": 14,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 130,
      "Calcium": 6,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Peach, 1 medium (147 g/5.3 oz)",
      "Calories": 60,
      "Calories�from Fat": 0,
      "Total Fat": 0.5,
      "Total Fat__1": 1,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 230,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 15,
      "Total Carbo-hydrate__1": 5,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 13,
      "Protein": 1,
      "Vitamin A": 6,
      "Vitamin C": 15,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Pear, 1 medium (166 g/5.9 oz)",
      "Calories": 100,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 190,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 26,
      "Total Carbo-hydrate__1": 9,
      "Dietary Fiber": 6,
      "Dietary Fiber__1": 24,
      "Sugars": 16,
      "Protein": 1,
      "Vitamin A": 0,
      "Vitamin C": 10,
      "Calcium": 2,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Pineapple, 2 slices, 3\" diameter,�3/4\" thick",
      "Calories": 50,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 10,
      "Sodium__1": 0,
      "Potassium": 120,
      "Potassium__1": 3,
      "Total Carbo-hydrate": 13,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 10,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 50,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Plums, 2 medium (151 g/5.4 oz)",
      "Calories": 70,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 230,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 19,
      "Total Carbo-hydrate__1": 6,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 16,
      "Protein": 1,
      "Vitamin A": 8,
      "Vitamin C": 10,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Strawberries, 8 medium (147 g/5.3 oz)",
      "Calories": 50,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 170,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 11,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 8,
      "Protein": 1,
      "Vitamin A": 0,
      "Vitamin C": 160,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Sweet�Cherries 21 cherries;�1 cup",
      "Calories": 100,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 350,
      "Potassium__1": 10,
      "Total Carbo-hydrate": 26,
      "Total Carbo-hydrate__1": 9,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 16,
      "Protein": 1,
      "Vitamin A": 2,
      "Vitamin C": 15,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Tangerine, 1 medium (109 g/3.9 oz)",
      "Calories": 50,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 160,
      "Potassium__1": 5,
      "Total Carbo-hydrate": 13,
      "Total Carbo-hydrate__1": 4,
      "Dietary Fiber": 2,
      "Dietary Fiber__1": 8,
      "Sugars": 9,
      "Protein": 1,
      "Vitamin A": 6,
      "Vitamin C": 45,
      "Calcium": 4,
      "��Iron��": 0,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Watermelon, 1/18 medium melon; 2 cups diced pieces(280 g/",
      "Calories": 80,
      "Calories�from Fat": 0,
      "Total Fat": 0,
      "Total Fat__1": 0,
      "Sodium": 0,
      "Sodium__1": 0,
      "Potassium": 270,
      "Potassium__1": 8,
      "Total Carbo-hydrate": 21,
      "Total Carbo-hydrate__1": 7,
      "Dietary Fiber": 1,
      "Dietary Fiber__1": 4,
      "Sugars": 20,
      "Protein": 1,
      "Vitamin A": 30,
      "Vitamin C": 25,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": "",
      "Saturated Fat__1": "",
      "Chole-sterol": "",
      "Chole-sterol__1": "",
      "Food Type": "Fruits Serving�Size (gram�weight/ounce�weight)"
    },
    {
      "Food and Serving": "Blue Crab",
      "Calories": 100,
      "Calories�from Fat": 10,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 330,
      "Sodium__1": 14,
      "Potassium": 300,
      "Potassium__1": 9,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 20,
      "Vitamin A": 0,
      "Vitamin C": 4,
      "Calcium": 10,
      "��Iron��": 4,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 95,
      "Chole-sterol__1": 32,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Catfish",
      "Calories": 130,
      "Calories�from Fat": 60,
      "Total Fat": 6,
      "Total Fat__1": 9,
      "Sodium": 40,
      "Sodium__1": 2,
      "Potassium": 230,
      "Potassium__1": 7,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 17,
      "Vitamin A": 0,
      "Vitamin C": 0,
      "Calcium": 0,
      "��Iron��": 0,
      "Saturated Fat": 2,
      "Saturated Fat__1": 10,
      "Chole-sterol": 50,
      "Chole-sterol__1": 17,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Clams, about 12 small",
      "Calories": 110,
      "Calories�from Fat": 15,
      "Total Fat": 1.5,
      "Total Fat__1": 2,
      "Sodium": 95,
      "Sodium__1": 4,
      "Potassium": 470,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 6,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 17,
      "Vitamin A": 10,
      "Vitamin C": 0,
      "Calcium": 8,
      "��Iron��": 30,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 80,
      "Chole-sterol__1": 27,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Cod",
      "Calories": 90,
      "Calories�from Fat": 5,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 65,
      "Sodium__1": 3,
      "Potassium": 460,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 20,
      "Vitamin A": 0,
      "Vitamin C": 2,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 50,
      "Chole-sterol__1": 17,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Flounder/Sole",
      "Calories": 100,
      "Calories�from Fat": 15,
      "Total Fat": 1.5,
      "Total Fat__1": 2,
      "Sodium": 100,
      "Sodium__1": 4,
      "Potassium": 390,
      "Potassium__1": 11,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 19,
      "Vitamin A": 0,
      "Vitamin C": 0,
      "Calcium": 2,
      "��Iron��": 0,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 55,
      "Chole-sterol__1": 18,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Haddock",
      "Calories": 100,
      "Calories�from Fat": 10,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 85,
      "Sodium__1": 4,
      "Potassium": 340,
      "Potassium__1": 10,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 21,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 2,
      "��Iron��": 6,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 70,
      "Chole-sterol__1": 23,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Halibut",
      "Calories": 120,
      "Calories�from Fat": 15,
      "Total Fat": 2,
      "Total Fat__1": 3,
      "Sodium": 60,
      "Sodium__1": 3,
      "Potassium": 500,
      "Potassium__1": 14,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 23,
      "Vitamin A": 4,
      "Vitamin C": 0,
      "Calcium": 2,
      "��Iron��": 6,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 40,
      "Chole-sterol__1": 13,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Lobster",
      "Calories": 80,
      "Calories�from Fat": 0,
      "Total Fat": 0.5,
      "Total Fat__1": 1,
      "Sodium": 320,
      "Sodium__1": 13,
      "Potassium": 300,
      "Potassium__1": 9,
      "Total Carbo-hydrate": 1,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 17,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 6,
      "��Iron��": 2,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 60,
      "Chole-sterol__1": 20,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Ocean Perch",
      "Calories": 110,
      "Calories�from Fat": 20,
      "Total Fat": 2,
      "Total Fat__1": 3,
      "Sodium": 95,
      "Sodium__1": 4,
      "Potassium": 290,
      "Potassium__1": 8,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 21,
      "Vitamin A": 0,
      "Vitamin C": 2,
      "Calcium": 10,
      "��Iron��": 4,
      "Saturated Fat": 0.5,
      "Saturated Fat__1": 3,
      "Chole-sterol": 45,
      "Chole-sterol__1": 15,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Orange Roughy",
      "Calories": 80,
      "Calories�from Fat": 5,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 70,
      "Sodium__1": 3,
      "Potassium": 340,
      "Potassium__1": 10,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 16,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 4,
      "��Iron��": 2,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 20,
      "Chole-sterol__1": 7,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Oysters, about 12 medium",
      "Calories": 100,
      "Calories�from Fat": 35,
      "Total Fat": 4,
      "Total Fat__1": 6,
      "Sodium": 300,
      "Sodium__1": 13,
      "Potassium": 220,
      "Potassium__1": 6,
      "Total Carbo-hydrate": 6,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 10,
      "Vitamin A": 0,
      "Vitamin C": 6,
      "Calcium": 6,
      "��Iron��": 45,
      "Saturated Fat": 1,
      "Saturated Fat__1": 5,
      "Chole-sterol": 80,
      "Chole-sterol__1": 27,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Pollock",
      "Calories": 90,
      "Calories�from Fat": 10,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 110,
      "Sodium__1": 5,
      "Potassium": 370,
      "Potassium__1": 11,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 20,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 80,
      "Chole-sterol__1": 27,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Rainbow Trout",
      "Calories": 140,
      "Calories�from Fat": 50,
      "Total Fat": 6,
      "Total Fat__1": 9,
      "Sodium": 35,
      "Sodium__1": 1,
      "Potassium": 370,
      "Potassium__1": 11,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 20,
      "Vitamin A": 4,
      "Vitamin C": 4,
      "Calcium": 8,
      "��Iron��": 2,
      "Saturated Fat": 2,
      "Saturated Fat__1": 10,
      "Chole-sterol": 55,
      "Chole-sterol__1": 18,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Rockfish",
      "Calories": 110,
      "Calories�from Fat": 15,
      "Total Fat": 2,
      "Total Fat__1": 3,
      "Sodium": 70,
      "Sodium__1": 3,
      "Potassium": 440,
      "Potassium__1": 13,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 21,
      "Vitamin A": 4,
      "Vitamin C": 0,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 40,
      "Chole-sterol__1": 13,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Salmon, Atlantic/Coho/Sockeye /Chinook",
      "Calories": 200,
      "Calories�from Fat": 90,
      "Total Fat": 10,
      "Total Fat__1": 15,
      "Sodium": 55,
      "Sodium__1": 2,
      "Potassium": 430,
      "Potassium__1": 12,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 24,
      "Vitamin A": 4,
      "Vitamin C": 4,
      "Calcium": 2,
      "��Iron��": 2,
      "Saturated Fat": 2,
      "Saturated Fat__1": 10,
      "Chole-sterol": 70,
      "Chole-sterol__1": 23,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Salmon,�Chum/Pink",
      "Calories": 130,
      "Calories�from Fat": 40,
      "Total Fat": 4,
      "Total Fat__1": 6,
      "Sodium": 65,
      "Sodium__1": 3,
      "Potassium": 420,
      "Potassium__1": 12,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 22,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": 1,
      "Saturated Fat__1": 5,
      "Chole-sterol": 70,
      "Chole-sterol__1": 23,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Scallops, about 6 large or 14 small",
      "Calories": 140,
      "Calories�from Fat": 10,
      "Total Fat": 1,
      "Total Fat__1": 2,
      "Sodium": 310,
      "Sodium__1": 13,
      "Potassium": 430,
      "Potassium__1": 12,
      "Total Carbo-hydrate": 5,
      "Total Carbo-hydrate__1": 2,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 27,
      "Vitamin A": 2,
      "Vitamin C": 0,
      "Calcium": 4,
      "��Iron��": 14,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 65,
      "Chole-sterol__1": 22,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Shrimp",
      "Calories": 100,
      "Calories�from Fat": 10,
      "Total Fat": 1.5,
      "Total Fat__1": 2,
      "Sodium": 240,
      "Sodium__1": 10,
      "Potassium": 220,
      "Potassium__1": 6,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 21,
      "Vitamin A": 4,
      "Vitamin C": 4,
      "Calcium": 6,
      "��Iron��": 10,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 170,
      "Chole-sterol__1": 57,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Swordfish",
      "Calories": 120,
      "Calories�from Fat": 50,
      "Total Fat": 6,
      "Total Fat__1": 9,
      "Sodium": 100,
      "Sodium__1": 4,
      "Potassium": 310,
      "Potassium__1": 9,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 16,
      "Vitamin A": 2,
      "Vitamin C": 2,
      "Calcium": 0,
      "��Iron��": 6,
      "Saturated Fat": 1.5,
      "Saturated Fat__1": 8,
      "Chole-sterol": 40,
      "Chole-sterol__1": 13,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Tilapia",
      "Calories": 110,
      "Calories�from Fat": 20,
      "Total Fat": 2.5,
      "Total Fat__1": 4,
      "Sodium": 30,
      "Sodium__1": 1,
      "Potassium": 360,
      "Potassium__1": 10,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 22,
      "Vitamin A": 0,
      "Vitamin C": 2,
      "Calcium": 0,
      "��Iron��": 2,
      "Saturated Fat": 1,
      "Saturated Fat__1": 5,
      "Chole-sterol": 75,
      "Chole-sterol__1": 25,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    },
    {
      "Food and Serving": "Tuna",
      "Calories": 130,
      "Calories�from Fat": 15,
      "Total Fat": 1.5,
      "Total Fat__1": 2,
      "Sodium": 40,
      "Sodium__1": 2,
      "Potassium": 480,
      "Potassium__1": 14,
      "Total Carbo-hydrate": 0,
      "Total Carbo-hydrate__1": 0,
      "Dietary Fiber": "",
      "Dietary Fiber__1": "",
      "Sugars": "",
      "Protein": 26,
      "Vitamin A": 2,
      "Vitamin C": 2,
      "Calcium": 2,
      "��Iron��": 4,
      "Saturated Fat": 0,
      "Saturated Fat__1": 0,
      "Chole-sterol": 50,
      "Chole-sterol__1": 17,
      "Food Type": "Seafood, Serving Size (84 g/3 oz)"
    }
  ]